export const Paths = {
  HOME: "/",
  USERS: "/users",
  USERS_CREATE: "/users/create",
  ADMIN_ROLES_CREATE: "/admin-roles/create",
  PROFILE: "/profile",
  ADMIN_ROLES: "/admin-roles",
  SUBSCRIPTIONS: "/subscriptions",
  WEBSITE_ANALYTICS: "/website-analytics",
  STOCK_ANALYSES: "/stock-analyses",
  STOCK_REPORT: "/stock-report",
  TOP_HALAL_STOCKS: "/top-halal-stocks",
  PORTFOLIOS: "/portfolios",
  FINANCE: "/finance",
  ARTICLES: "/articles",
  WEBINARS: "/webinars",
  SUPPORT_TICKETS: "/support-tickets",
  NOTIFICATIONS: "/notifications",
  SETTINGS: "/settings",
  NOT_FOUND: "*",
  LOGIN: "/login",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  CHECK_YOUREMAIL: "/check-your-email",
  SET_NEW_PASSWORD: "/set-new-password",
  PASSWORD_RESET: "/password-reset",
  PERSONAL_INFO: "/personal-info"
};
